# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGlobalIrradiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horizontal_kaplanis', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyGlobalIrradiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_kaplanis_whillier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('direct_kaplanis_whillier_erbs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diffuse_kaplanis_whillier_erbs', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
