# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-30 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourlyglobalirradiance',
            old_name='diffuse_kaplanis_whillier_erbs',
            new_name='diffuse_kaplanis_lj_erbs',
        ),
        migrations.RenameField(
            model_name='hourlyglobalirradiance',
            old_name='direct_kaplanis_whillier_erbs',
            new_name='direct_kaplanis_lj_erbs',
        ),
        migrations.RenameField(
            model_name='hourlyglobalirradiance',
            old_name='total_kaplanis_whillier',
            new_name='total_kaplanis_lj',
        ),
    ]
