# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-30 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solar_models', '0002_auto_20180630_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyglobalirradiance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyglobalirradiance',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
