# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_models', '0003_auto_20180630_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyglobalirradiance',
            name='diffuse_kaplanis_lj_erbs',
        ),
        migrations.RemoveField(
            model_name='hourlyglobalirradiance',
            name='direct_kaplanis_lj_erbs',
        ),
    ]
