# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_models', '0004_auto_20180713_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyglobalirradiance',
            name='horizontal_kaplanis',
        ),
        migrations.AddField(
            model_name='dailyglobalirradiance',
            name='horizontal_CMSAF',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dailyglobalirradiance',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
            preserve_default=False,
        ),
    ]
