# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_models', '0006_auto_20180718_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyglobalirradiance',
            name='horizontal_CMSAF',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
